source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DYSCategories_Example', :exclusive => true do
  pod "DYSCategories", :path => "../"
end

target 'DYSCategories_Tests', :exclusive => true do
  pod "DYSCategories", :path => "../"

  
end
